### ISSUE TITLE
È tt empty!!

### ISSUE THREAD

**Issue by alsoGAMER** [peppelg/madeline.py#1]
ucsa put qualche things
![image](https://user-images.githubusercontent.com/35269770/54880629-e0efcd00-4e46-11e9-8aff-8cbdc056f1dc.png)

**Comment by peppelg** [comment]
ee minghia lo devo continuare ero arrivato a 1O righe,.,se c'è wualcuno che conosce bene pitone e mi può aiutare mi scriva nel gram in pvt che col teletype lo .famo

**Comment by alsoGAMER** [comment]
@Evolvere sul gramz
